/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: process.env.REACT_APP_AWS_USER_POOLS_ID as string,
  aws_user_pools_web_client_id: process.env
    .REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID as string,
  oauth: {},
  aws_cognito_login_mechanisms: ['EMAIL'],
  aws_cognito_signup_attributes: [
    'EMAIL',
    'FAMILY_NAME',
    'NAME',
    'PHONE_NUMBER',
    'PICTURE',
  ],
  aws_cognito_mfa_configuration: 'OPTIONAL',
  aws_cognito_mfa_types: ['SMS', 'TOTP'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['PHONE_NUMBER'],
};

export default awsConfig;
